services:
  gametts:
    build: .
    container_name: gametts
    ports:
      - 127.0.0.1:8001:8000
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 2G
          pids: 50
    healthcheck:
      test: curl -f http://127.0.0.1:8000/get_games || exit 1
      interval: 30s
      retries: 3
    restart: unless-stopped
