import typing

SPEECH_STYLE_DEFAULT = 'Default'
SPEECH_STYLE_DRUNK = 'Drunk'
SPEECH_STYLE_FRENCH = 'French'
SPEECH_STYLE_GNOME = 'Gnome'
SPEECH_STYLE_OGRE = 'Ogre'
SPEECH_STYLE_PIRATE = 'Pirate'
SPEECH_STYLE_WEIRD = 'Weird'

SPEECH_STYLE = {
    SPEECH_STYLE_DEFAULT: 0,
    SPEECH_STYLE_PIRATE: 28,
    SPEECH_STYLE_WEIRD: 157,
    SPEECH_STYLE_DRUNK: 90,
    SPEECH_STYLE_OGRE: 37,
    SPEECH_STYLE_GNOME: 206,
}

EMOTION_ANGER = 'Anger'
EMOTION_CALM = 'Calm'
EMOTION_DISGUST = 'Disgust'
EMOTION_FEAR = 'Fear'
EMOTION_HAPPY = 'Happy'
EMOTION_NEUTRAL = 'Neutral'
EMOTION_SURPRISED = 'Surprised'

EMOTION = {
    EMOTION_ANGER: 0,
    EMOTION_CALM: 1,
    EMOTION_DISGUST: 2,
    EMOTION_FEAR: 3,
    EMOTION_HAPPY: 4,
    EMOTION_NEUTRAL: 5,
    EMOTION_SURPRISED: 6,
}
